# 上昇トレンド追従
target_currency = "mona"
interval_seconds = 10

# 買い注文1回に使う日本円残高の割合
funds_ratio = 0.3

# 売り注文時のレート上乗せ分(%)
# 売り注文レート = 買い注文のレート × (1 + upRate)
up_rate = 0.005

# 売り注文をロスカットする下限の割合
# 現レートが下限を下回るとロスカットする
# 下限 = 注文レート * 下限の割合
loss_cut_lower_limit_per = 0.990

# 約定チェック間隔
contract_check_interval_seconds = 2

# 同時に持てるポジションの最大数
position_count_max = 1

# 短期を確認する際の確認対象レート数
short_term_size = 5

# 長期を確認する際の確認対象レート数
long_term_size = 30
