# スキャルピング
target_currency = "mona"
interval_seconds = 10
position_count_max = 1
funds_ratio = 0.3

short_term_size = 32
long_term_size = 174
loss_cut_lower_limit_per = 0.927
fis_profit_upper_limit_per = 1.593
bbands_nb_dev_up = 3.0
bbands_nb_dev_down = 2.2967
rsi_lower = 20.0
rsi_upper = 80.0
