# シミュレーター
strategy_name = "follow_uptrend"
target_currency = "btc"
rate_history_size = 15
slippage = 0.001

# DB設定
[db]
host = "simulation-db"
port = 3306
name = "trading-bot"
user_name = "bot"
password = "P@ssw0rd"
